-- 003_force_rls.sql
-- Force row-level security even for table owners. Combined with the split
-- roles (002) where migrator=BYPASSRLS and app=NOBYPASSRLS, this ensures
-- the runtime role is strictly subject to tenant policies from 001.
--
-- Run after 001 + 002. Idempotent.

do $$
declare
  t text;
  tables text[] := array[
    'organizations',
    'memberships',
    'organization_memberships',
    'buildings',
    'assets',
    'obligation_templates',
    'obligation_bases',
    'applicability_rules',
    'building_obligations',
    'ppm_templates',
    'ppm_plan_items',
    'task_instances',
    'ppm_execution_logs',
    'budgets',
    'budget_lines',
    'invoices',
    'approval_requests',
    'approval_steps',
    'documents',
    'audit_entries',
    'building_role_assignments',
    'building_mandates',
    'import_jobs',
    'import_job_rows',
    'engineering_recommendations',
    'projects',
    'work_orders',
    'takeover_cases',
    'parking_spots',
    'storage_units',
    'equipment_relations',
    'elevator_profiles',
    'document_links',
    'incidents',
    'service_requests',
    'quotes',
    'purchase_orders',
    'completion_records',
    'inventory_items',
    'stock_locations',
    'stock_movements',
    'qr_locations',
    'entrances',
    'floors',
    'units',
    'vendors',
    'contracts',
    'accounts',
    'notifications',
    'building_floors',
    'building_units',
    'building_vertical_transport',
    'building_systems',
    'building_occupant_companies',
    'building_unit_occupancies',
    'building_contracts',
    'compliance_profiles',
    'building_compliance_profiles',
    'sensor_points',
    'alarm_sources',
    'vendor_invoices',
    'emergency_overrides',
    'calendar_blackouts',
    'condition_triggers',
    'condition_events',
    'project_stages',
    'project_budget_lines',
    'change_orders',
    'acceptance_packs',
    'tenant_representatives',
    'approval_policies',
    'approval_delegations',
    'outbox_events',
    'webhook_subscriptions',
    'inbound_webhook_sources',
    'inbound_webhook_events',
    'personal_data_categories',
    'dsar_requests',
    'identity_providers',
    'oidc_login_states',
    'scim_tokens',
    'signed_urls',
    'subprocessor_registry',
    'dpa_templates',
    'cleaning_contractors',
    'cleaning_roles',
    'cleaning_staff',
    'cleaning_zones',
    'cleaning_qr_points',
    'cleaning_requests',
    'cleaning_request_comments',
    'cleaning_request_attachments',
    'cleaning_request_history',
    'building_locations',
    'document_templates',
    'rounds',
    'round_waypoints',
    'round_instances',
    'round_instance_answers',
    'asset_types',
    'asset_custom_attributes',
    'asset_documents',
    'asset_media',
    'asset_spare_parts',
    'seed_runs'
  ];
begin
  foreach t in array tables loop
    execute format('alter table %I force row level security', t);
  end loop;
end $$;
